export const PersonReducers = {
  personDetail: [
    {
      id: "1asdf",
      name: "Sam",
      age: 20,
      description: "He is a 1st year student",
      image: "Assets/Rose.jpg",
    },
    {
      id: "2asdf",
      name: "Mazhar",
      age: 21,
      description: `He is a 2nr year student`,
      image: "Assets/Rose.jpg",
    },
    {
      id: "3asdf",
      name: "Rizwan",
      age: 22,
      description: `He is a 3rd year student`,
      image: "Assets/Rose.jpg",
    },
    {
      id: "4asdf",
      name: "Aadil",
      age: 23,
      description: `He is a 12th student`,
      image: "Assets/Rose.jpg",
    },
    {
      id: "5asdf",
      name: "Zahoor",
      age: 24,
      description: `He is a 11th student`,
      image: "Assets/Rose.jpg",
    },
    {
      id: "6asdf",
      name: "Mujahed",
      age: 25,
      description: `He is a 10th student`,
      image: "Assets/Rose.jpg",
    },
    {
      id: "7asdf",
      name: "Kaleem",
      age: 26,
      description: `He is a 9th student`,
      image: "Assets/Rose.jpg",
    },
    {
      id: "8asdf",
      name: "Zubair",
      age: 27,
      description: `He is a 8th student`,
      image: "Assets/Rose.jpg",
    },
    {
      id: "9asdf",
      name: "Aamer",
      age: 28,
      description: `He is a 7th student`,
      image: "Assets/Rose.jpg",
    },
  ],
};
